const PREFAB_HOUSE_IDS = new Set(
  'abcdefghijklmnopqrstu'.split('').map(letter => `prefab_house_${letter}`)
)

const DIRECTION_ORDER = [2, 1, 0, 3]
const DEFAULT_PREFAB_PROFILE = {
  scale: 1.22,
  yOffset: 0.06,
  entranceDistance: 1,
  lotPadding: 1,
}

const PREFAB_PROFILES = {
  prefab_house_a: { scale: 1.34, yOffset: 0.08, entranceDistance: 1 },
  prefab_house_b: { scale: 1.3, yOffset: 0.08, entranceDistance: 1 },
  prefab_house_c: { scale: 1.32, yOffset: 0.08, entranceDistance: 1 },
  prefab_house_d: { scale: 1.28, yOffset: 0.07, entranceDistance: 1 },
  prefab_house_e: { scale: 1.24, yOffset: 0.07, entranceDistance: 1 },
  prefab_house_f: { scale: 1.28, yOffset: 0.07, entranceDistance: 1 },
  prefab_house_g: { scale: 1.24, yOffset: 0.07, entranceDistance: 1 },
  prefab_house_h: { scale: 1.26, yOffset: 0.07, entranceDistance: 1 },
  prefab_house_i: { scale: 1.26, yOffset: 0.07, entranceDistance: 1 },
  prefab_house_j: { scale: 1.28, yOffset: 0.07, entranceDistance: 1 },
  prefab_house_k: { scale: 1.18, yOffset: 0.06, entranceDistance: 1 },
  prefab_house_l: { scale: 1.18, yOffset: 0.06, entranceDistance: 1 },
  prefab_house_m: { scale: 1.34, yOffset: 0.08, entranceDistance: 1 },
  prefab_house_n: { scale: 1.32, yOffset: 0.08, entranceDistance: 1 },
  prefab_house_o: { scale: 1.24, yOffset: 0.07, entranceDistance: 1 },
  prefab_house_p: { scale: 1.28, yOffset: 0.07, entranceDistance: 1 },
  prefab_house_q: { scale: 1.28, yOffset: 0.07, entranceDistance: 1 },
  prefab_house_r: { scale: 1.18, yOffset: 0.06, entranceDistance: 1 },
  prefab_house_s: { scale: 1.2, yOffset: 0.06, entranceDistance: 1 },
  prefab_house_t: { scale: 1.24, yOffset: 0.07, entranceDistance: 1 },
  prefab_house_u: { scale: 1.22, yOffset: 0.06, entranceDistance: 1 },
}

function isPrefabAsset(assetId) {
  return PREFAB_HOUSE_IDS.has(assetId)
}

function getPrefabProfile(prefabId) {
  return {
    ...DEFAULT_PREFAB_PROFILE,
    ...(PREFAB_PROFILES[prefabId] ?? {}),
  }
}

function canPlace(gridManager, x, z) {
  const topCell = gridManager.getTopCell(x, z)
  return !topCell || (topCell.y === 0 && !topCell.metadata?.reservedBy)
}

function createPlan(gridManager, x, z, prefabId) {
  if (!isPrefabAsset(prefabId) || !canPlace(gridManager, x, z)) return null

  const profile = getPrefabProfile(prefabId)
  const entranceDirection = _pickEntranceDirection(gridManager, x, z)
  const [dx, dz] = _directionOffset(entranceDirection)
  const prefabInstanceId = `${prefabId}:${x}_1_${z}`
  const driveway = {
    x: x + dx * profile.entranceDistance,
    y: 0,
    z: z + dz * profile.entranceDistance,
  }
  const addCells = []
  const updateCells = []
  const planned = new Set()

  if (!gridManager.hasCell(x, 0, z)) {
    _pushAdd(addCells, planned, {
      x,
      y: 0,
      z,
      material: 'stone_quay',
      metadata: {
        reservedBy: prefabInstanceId,
        reservationRole: 'prefab_footprint',
        prefabProfile: prefabId,
      },
    })
  } else {
    updateCells.push({
      x,
      y: 0,
      z,
      metadata: {
        reservedBy: prefabInstanceId,
        reservationRole: 'prefab_footprint',
        prefabProfile: prefabId,
      },
    })
  }

  _pushAdd(addCells, planned, {
    x,
    y: 1,
    z,
    material: 'suburban',
    metadata: {
      prefabId,
      prefabInstanceId,
      prefabRotation: _rotationFromDirection(entranceDirection),
      prefabScale: profile.scale,
      prefabYOffset: profile.yOffset,
      prefabProfile: prefabId,
      entranceSide: _sideNameFromDirection(entranceDirection),
      entranceDirection,
      entranceCell: driveway,
      footprint: [{ x, y: 0, z }],
    },
  })

  const drivewayTop = gridManager.getTopCell(driveway.x, driveway.z)
  if (!drivewayTop) {
    _pushAdd(addCells, planned, {
      ...driveway,
      material: 'stone_quay',
      metadata: {
        autoGenerated: true,
        autoReason: 'prefab_entrance',
        ownerPrefabInstanceId: prefabInstanceId,
        ownerPrefabId: prefabId,
        surfaceAssetType: 'surface_entrance',
        surfaceRole: 'entrance',
        surfaceDirection: entranceDirection,
      },
    })
  } else if (drivewayTop.y === 0) {
    updateCells.push({
      x: driveway.x,
      y: 0,
      z: driveway.z,
      metadata: {
        ownerPrefabInstanceId: prefabInstanceId,
        ownerPrefabId: prefabId,
        surfaceAssetType: 'surface_entrance',
        surfaceRole: 'entrance',
        surfaceDirection: entranceDirection,
      },
    })
  }

  for (const yard of _lotFoundationCells(x, z, entranceDirection, profile)) {
    if (gridManager.getTopCell(yard.x, yard.z) || planned.has(_cellKey(yard.x, yard.y, yard.z))) continue
    _pushAdd(addCells, planned, {
      ...yard,
      material: 'stone_quay',
      metadata: {
        autoGenerated: true,
        autoReason: yard.role === 'backyard' ? 'prefab_backyard' : 'prefab_side_yard',
        ownerPrefabInstanceId: prefabInstanceId,
        ownerPrefabId: prefabId,
        surfaceAssetType: yard.role === 'backyard' ? 'surface_plaza_center' : 'surface_plaza_edge',
        surfaceRole: 'plaza',
        surfaceDirection: yard.direction,
      },
    })
  }

  return {
    prefabId,
    entranceDirection,
    addCells,
    updateCells,
    affectedPositions: [
      { x, y: 0, z },
      { x, y: 1, z },
      driveway,
      ..._lotFoundationCells(x, z, entranceDirection, profile),
    ],
  }
}

const PrefabPlacementMode = {
  isPrefabAsset,
  getPrefabProfile,
  canPlace,
  createPlan,
}

export { PrefabPlacementMode, getPrefabProfile }

function _pickEntranceDirection(gridManager, x, z) {
  const supported = DIRECTION_ORDER.filter(direction => {
    const [dx, dz] = _directionOffset(direction)
    const topCell = gridManager.getTopCell(x + dx, z + dz)
    return topCell?.y === 0 && !topCell.metadata?.reservedBy
  })
  if (supported.length > 0) return supported[0]

  const open = DIRECTION_ORDER.filter(direction => {
    const [dx, dz] = _directionOffset(direction)
    return !gridManager.getTopCell(x + dx, z + dz)
  })
  return open[0] ?? 2
}

function _lotFoundationCells(x, z, entranceDirection, profile) {
  if ((profile.lotPadding ?? 0) <= 0) return []

  const back = _oppositeDirection(entranceDirection)
  const sideDirs = entranceDirection === 0 || entranceDirection === 1 ? [2, 3] : [0, 1]
  const cells = []

  for (const direction of sideDirs) {
    const [dx, dz] = _directionOffset(direction)
    cells.push({
      x: x + dx,
      y: 0,
      z: z + dz,
      direction,
      role: 'side_yard',
    })
  }

  const [bdx, bdz] = _directionOffset(back)
  cells.push({
    x: x + bdx,
    y: 0,
    z: z + bdz,
    direction: back,
    role: 'backyard',
  })

  return cells
}

function _pushAdd(addCells, planned, spec) {
  const key = _cellKey(spec.x, spec.y, spec.z)
  if (planned.has(key)) return
  planned.add(key)
  addCells.push(spec)
}

function _cellKey(x, y, z) {
  return `${x}_${y}_${z}`
}

function _oppositeDirection(direction) {
  if (direction === 0) return 1
  if (direction === 1) return 0
  if (direction === 2) return 3
  return 2
}

function _directionOffset(direction) {
  if (direction === 0) return [-1, 0]
  if (direction === 1) return [1, 0]
  if (direction === 2) return [0, 1]
  return [0, -1]
}

function _sideNameFromDirection(direction) {
  if (direction === 0) return 'west'
  if (direction === 1) return 'east'
  if (direction === 3) return 'north'
  return 'south'
}

function _rotationFromDirection(direction) {
  if (direction === 0) return Math.PI / 2
  if (direction === 1) return -Math.PI / 2
  if (direction === 3) return Math.PI
  return 0
}
